<div id="cti_menubuilder_fields" class="cti_menubuilder_panel_right visibly-hidden">
    <div class="entry-edit">
        <?php echo $this->getFormHtml(); ?>

        <button id="save_menu_item" class="scalable save" type="button" title="Save Item">
            <span>
                <span>
                    <span><?php echo $this->__('Save Item') ?></span>
                </span>
            </span>
        </button>
    </div>
</div>